name: Auto-updater
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: SSH to the server and update the code
        uses: ./
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.NAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command: cd /root/searchpets/scripts && bash update.sh
